config/routes.rb
Rails.application.routes.draw do

  get '/my_cruds' => 'display#my_cruds'
  get '/not_authorised' => 'welcome#not_authorised'
  delete '/logout' => 'welcome#session_destroy'

  root 'home#index'
  get '/draw_graph' => 'welcome#draw_graph'
  get '/api/master_reports_count' => 'display#master_reports_count'
  get '/api/cruds_count' => 'display#cruds_count'
  get '/api/user_cruds' => 'display#user_cruds'

  resources :welcome

  post "dbcredentials" => "welcome#dbcredentials"
  get "msttablelisting" => "welcome#msttablelisting"
  get "tablelisting" => "welcome#tablelisting"
  get 'table_info/:table' => "welcome#table_info", :as => :table_info
  post 'create_crud/:table' => "welcome#create_crud", :as => :create_crud
  get 'controller_list' => "welcome#controller_list"
  get 'mst_controller_list' => "welcome#mst_controller_list"
  get '/download_data' => 'display#download_data'
  post 'sign_in' => 'home#sign_in'

  resources :display 

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #skip_before_filter :verify_session, :only => [:not_authorised, :session_destroy]

  def index
    #session[:user] = params[:email] if params[:email]
  end
@db;
  def dbcredentials
    host = params[:host].strip
    adapter = params[:adapter].strip
    db = params[:db].strip
    username = params[:username].strip
    password = params[:password].strip
    session[:db] = db
    session[:adapter] = adapter
    old_connection = ActiveRecord::Base.remove_connection
    begin 
    new_connection = ActiveRecord::Base.establish_connection(
      adapter:  adapter,
      host:     host,
      username: username,
      password: password,
      database: db
    )
    @tables = ActiveRecord::Base.connection.tables
    #rescue ActiveRecord::NoDatabaseError
    #  redirect_to "/welcome", :notice => "Invalid Credentials" and return
    rescue ActiveRecord::NoDatabaseError
      redirect_to '/welcome', :notice => 'Invalid Credentials' and return
   rescue 
      redirect_to '/welcome', :notice => 'Invalid Credentials' and return
    end
   redirect_to "/tablelisting"
  end

  def tablelisting
  @dbTable = session[:db]
  @adapter = session[:adapter]  
   # @tables = ActiveRecord::Base.connection.tables
	#@tables = MasterGdi.find_by_sql("SHOW FULL TABLES IN gdioperations WHERE TABLE_TYPE LIKE '%TABLE%'") 
  #raise @adapter
  if @adapter == 'postgresql'
      @tables = Welcome.connection.execute("SELECT tablename FROM pg_catalog.pg_tables where schemaname='public'") 
      print @tables
  else
	    @tables = Welcome.connection.execute("SHOW FULL TABLES IN #{@dbTable} WHERE TABLE_TYPE LIKE '%TABLE%'")
  end
	  session[:db]=''
    session[:adapter]=''
  end

  def table_info
    @table = params[:table].strip
    
    @table_info = ActiveRecord::Base.connection.columns(@table)
    @routes= Rails.application.routes.routes.map do |route|
  #{alias: route.name, path: route.path.spec.to_s, controller: route.defaults[:controller], action: route.defaults[:action]}
end
  end

   def create_crud
    #raise params.inspect
    db_config = ActiveRecord::Base.connection_config
    #raise db_config.inspect 
    @scaffold = params[:table].strip
    @table_info = Welcome.connection.columns(@scaffold)
    @colms = @table_info.map {|c| [c.name,c.type.to_s,params[c.name]]}
    #@colums = @table_info.map {|c| c.name + ":" + c.type.to_s + " "}.join(" ")
    @colms = @colms.map {|c| c.flatten.compact}
    @for_scaff = @colms.map {|c| c.join(":")}.join(" ")
    #ActiveRecord::Base.connection.query_cache.clear
    #raise db_config[:database].inspect
    #raise @for_scaff.inspect
    #@table_info = ActiveRecord::Base.connection.columns(@scaffold)
    #@colums = @table_info.map {|c| c.name + ":" + c.type.to_s + " "}.join(" ")
   # system "rails g scaffold #{@scaffold} #{@colums}--skip-migration --no-stylesheets --skip"
   now = Time.now.to_i
  # UserCrud.create(:crud_name => @scaffold, :crud_link => @scaffold.pluralize.underscore, :db_name => db_config[:database], :email => session[:user])
   #user_crud = UserCrud.new
   #user_crud.email = session['user']
   #user_crud.crud_name = @scaffold
   #user_crud.crud_link = @scaffold.pluralize.underscore
   #user_crud.db_name = db_config[:database]
   #user_crud.bundle_name = now.to_s + '-' + crud_name
   #user_crud.save
   #raise user_crud.inspect
    system "rails g almond #{@scaffold} #{@for_scaff} --database-name=#{db_config[:database]} --username=#{db_config[:username]} --password=#{db_config[:password]} --host=#{db_config[:host]} --now=#{now} --force"


  #  model_file_name = @scaffold.singularize.underscore
  #  database_config = ActiveRecord::Base.connection_config 
  #  model = <<-CODE
#	class #{model_file_name.classify} < ActiveRecord::Base
#		self.table_name = '#{@scaffold}'
 #               #{database_config}
  #              ActiveRecord::Base.establish_connection(#{database_config})
#	end
 #   CODE

   #File.open(Rails.root + "app/models/#{model_file_name.chomp('s')}.rb", 'w+') {|f| f.write(model) }
   
   # redirect_to "/controller_list"
   redirect_to "/#{@scaffold.pluralize.underscore}"
   #  redirect_to "/my_cruds"
  end

def controller_list
   # @listcontrollers = Dir[Rails.root.join('app/controllers/*_controller.rb')].map { |path|(path.match(/(\w+)_controller.rb/); $1).camelize}  
     @listcontrollers = Dir[Rails.root.join('app/controllers/*_controller.rb')].map { |path| path.match(/(\w+)_controller.rb/); $1 }.compact

end

def mst_controller_list
   # @listcontrollers = Dir[Rails.root.join('app/controllers/*_controller.rb')].map { |path|(path.match(/(\w+)_controller.rb/); $1).camelize}  
     @listcontrollers = Dir[Rails.root.join('app/controllers/gdi_mst*.rb')].map { |path| path.match(/(\w+)_controller.rb/); $1 }.compact

end

 def msttablelisting
   

   # @tables = ActiveRecord::Base.connection.tables
	@tables = Welcome.connection.execute("SHOW FULL TABLES IN gdioperations WHERE TABLE_TYPE LIKE '%TABLE%'") 
	#@tables = Welcome.connection.execute("SHOW FULL TABLES IN #{@dbTable} WHERE TABLE_TYPE LIKE '%TABLE%'")
	  
  end
  
  def draw_graph
   model = params['model'].constantize
   
  end
  
  def not_authorised
  end

  def session_destroy
    session[:user] = nil
    redirect_to '/'    
  end
 
end

app/views/welcome/controller_list.html.erb
                         <div class="widget-body">
				<h2>List of all Controller Paths</h2>
				<table> 
					<tr> 
						<th> Path </th>
						<th> Link </th>
					</tr>

				<% @listcontrollers.each do |listcontrollers| %>
				<tr>
						<td> <%= listcontrollers %> </td>
						<td> <%= link_to listcontrollers, listcontrollers, class: "btn" %> </td>
				</tr>
				<%end%>
				</table>
				</div>


				
	

app/views/welcome/draw_graph.js.erb
$(function () {

    $('#dynamic_chart').highcharts({

        chart: {
            type: 'column',
        },
        credits: {
          enabled: false
        },
        legend: {
            enabled: true,
                layout: 'horizontal',
                align: 'right',
                        verticalAlign: 'middle',
            labelFormatter: function() {
                                return this.name + " - <span class='total'>"+this.y+"</span>"
            }
        },
        title: {
            text: 'No of Forums'
        },
        xAxis: {
            categories: ['First', 'Second', 'Third', 'Fourth', , 'Fifth'],
            allowDecimals: false
        },
        yAxis: {
            allowDecimals: false
        },

        series: [
            {
                showInLegend: false,
                data: [
                    {y: 6, name: 'First', color: 'blue'},
                    {y: 7, name: 'Second', color: 'green'},
                    {y: 9, name: 'Third', color: 'yellow'},
                    {y: 1, name: 'Fourth', color: 'orange'},
                    {y: 1, name: 'Fifth', color: 'red'}
                ]
            }
        ],

    });

});

//$("#modal_data").html("<%#= escape_javascript(render :partial => 'graphs') %>");

app/views/welcome/home.html.erb
<h1>Welcome#home</h1>

<%= form_tag("/dbcredentials", method: "post") do %>
  <%= label_tag :host %>
  <%= text_field_tag :host %><br />

  <%= label_tag :adapter %>
  <%= text_field_tag :adapter %><br />

  <%= label_tag :db %>
  <%= text_field_tag :db %><br />

  <%= label_tag :username %>
  <%= text_field_tag :username %><br />

  <%= label_tag :password %>
  <%= password_field_tag :password %><br />

  <%= submit_tag("Connect") %>
<% end %>

app/views/welcome/index.html.erb
<div class="widget-body">
  <center>
    <h1>Welcome to Automatic CRUD Creation</h1>
    <div style="width:75%;">
      <%= form_tag("/dbcredentials", method: "post") do %>
        <%= label_tag :host %>
        <%= text_field_tag :host %><br />
        <%= label_tag :adapter %>
        <%= text_field_tag :adapter, 'mysql2' %><br />
        <%= label_tag :db %>
        <%= text_field_tag :db %><br />
        <%= label_tag :username %>
        <%= text_field_tag :username %><br />
        <%= label_tag :password %>
        <%= password_field_tag :password %>
	<div>
          <%= submit_tag("Connect") %>
	</div>
      <% end %>
    </div>
  </center>
</div>

app/views/welcome/index2.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Metro Lab</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="Mosaddek" name="author" />

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
  
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <!-- BEGIN THEME CUSTOMIZER-->
                   
                   <!-- END THEME CUSTOMIZER-->
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     Dashboard
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="#">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">Database Credentials</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                          Show All Tables
			  <span class="divider">/</span>

                       </li>
			<li class="active">
                          Table Summary
			  <span class="divider">/</span>

                       </li>

                       <li class="pull-right search-wrap">
                           <form action="search_result.html" class="hidden-phone">
                               <div class="input-append search-input-area">
                                   <input class="" id="appendedInputButton" type="text">
                                   <button class="btn" type="button"><i class="icon-search"></i> </button>
                               </div>
                           </form>
                       </li>
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
             <div class="row-fluid">
                 <div class="span12">
                     <!-- BEGIN BLANK PAGE PORTLET-->
                     <div class="widget red">
                         <div class="widget-title">
                             <h4><i class="icon-edit"></i> Table Listing </h4>
                           <span class="tools">
                               <a href="javascript:;" class="icon-chevron-down"></a>
                               <a href="javascript:;" class="icon-remove"></a>
                           </span>
                         </div>
                         <div class="widget-body">
				<h2>Table info <b><%= @table %></b></h2>
					<% @table_info.each do |c| %>
  					<%= c.name + ": " + c.type.to_s%><br />
						<% end %>
						<%= link_to "Create Crud", create_crud_path(@table) %>                         </div>
                     </div>
                     <!-- END BLANK PAGE PORTLET-->
                 </div>
             </div>
            <!-- END PAGE CONTENT-->   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
       2015 &copy; Deepak Kalhan
   </div>
    
</body>
<!-- END BODY -->
</html>

app/views/welcome/mst_controller_list.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Metro Lab</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="Mosaddek" name="author" />

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
  
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <!-- BEGIN THEME CUSTOMIZER-->
                   
                   <!-- END THEME CUSTOMIZER-->
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     Dashboard
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="#">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">Database Credentials</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                          Show All Tables
			  <span class="divider">/</span>

                       </li>
			<li class="active">
                          Table Summary
			  <span class="divider">/</span>

                       </li>

                       <li class="pull-right search-wrap">
                           <form action="search_result.html" class="hidden-phone">
                               <div class="input-append search-input-area">
                                   <input class="" id="appendedInputButton" type="text">
                                   <button class="btn" type="button"><i class="icon-search"></i> </button>
                               </div>
                           </form>
                       </li>
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
             <div class="row-fluid">
                 <div class="span12">
                     <!-- BEGIN BLANK PAGE PORTLET-->
                     <div class="widget red">
                         <div class="widget-title">
                             <h4><i class="icon-edit"></i> Table Summary </h4>
                           <span class="tools">
                               <a href="javascript:;" class="icon-chevron-down"></a>
                               <a href="javascript:;" class="icon-remove"></a>
                           </span>
                         </div>
                         <div class="widget-body">
				<h2>List of all Controller Paths</h2>
				<table> 
					<tr> 
						<th> Path </th>
						<th> Link </th>
					</tr>

				<% @listcontrollers.each do |listcontrollers| %>
				<tr>
						<td> <%= listcontrollers %> </td>
						<td> <%= link_to listcontrollers, listcontrollers, target: "_blank", class: "btn" %> </td>
				</tr>
				<%end%>
				</table>
				</div>


				
	
                     </div>
                     <!-- END BLANK PAGE PORTLET-->
                 </div>
             </div>
            <!-- END PAGE CONTENT-->   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
       2015 &copy; Deepak Kalhan
   </div>
    
</body>
<!-- END BODY -->
</html>

app/views/welcome/msttablelisting.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
   <meta charset="utf-8" />
   <title>Metro Lab</title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="Mosaddek" name="author" />

</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="fixed-top">
   <!-- BEGIN HEADER -->
  
   <!-- BEGIN CONTAINER -->
   <div id="container" class="row-fluid">
      
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE HEADER-->   
            <div class="row-fluid">
               <div class="span12">
                   <!-- BEGIN THEME CUSTOMIZER-->
                   
                   <!-- END THEME CUSTOMIZER-->
                  <!-- BEGIN PAGE TITLE & BREADCRUMB-->
                   <h3 class="page-title">
                     Dashboard
                   </h3>
                   <ul class="breadcrumb">
                       <li>
                           <a href="#">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">Database Credentials</a>
                           <span class="divider">/</span>
                       </li>
                       <li class="active">
                          Show All Tables
                       </li>
                       <li class="pull-right search-wrap">
                           <form action="search_result.html" class="hidden-phone">
                               <div class="input-append search-input-area">
                                   <input class="" id="appendedInputButton" type="text">
                                   <button class="btn" type="button"><i class="icon-search"></i> </button>
                               </div>
                           </form>
                       </li>
                   </ul>
                   <!-- END PAGE TITLE & BREADCRUMB-->
               </div>
            </div>
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
             <div class="row-fluid">
                 <div class="span12">
                     <!-- BEGIN BLANK PAGE PORTLET-->
                     <div class="widget red">
                         <div class="widget-title">
                             <h4>Table Listing of <%= @dbTable %> Schema</h4>
                           <span class="tools">
                               <a href="javascript:;" class="icon-chevron-down"></a>
                               <a href="javascript:;" class="icon-remove"></a>
                           </span>
                         </div>
                         <div class="widget-body">
						<table>
						<tr>
							<th> Table Name </th>
							<th> Info List </th>
							<th> Create CRUD </th>
						</tr>
						<% @tables.each do |table| %>
						<tr>
							<td> <%= table[0] %> </td>
							<td> <%= link_to "Table info", table_info_path(table[0]), class: "btn" %> </td>
							<td> <%= link_to "Create CRUD", create_crud_path(table[0]), class: "btn" %> </td>
						</tr>
						<% end %>
						</table>
						 </div>
                     </div>
                     <!-- END BLANK PAGE PORTLET-->
                 </div>
             </div>
            <!-- END PAGE CONTENT-->   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
       2015 &copy; Deepak Kalhan
   </div>
    
</body>
<!-- END BODY -->
</html>

app/views/welcome/not_authorised.html.erb
<h3>You are not authorised to view this page</h3>

app/views/welcome/table_info.html.erb
<div class="widget-body">
  <h2>Table info <b><%= @table %></b></h2>
  <%#= @table_info.inspect %>
  <table border=2>
    <tr>
      <th> Column Names </th>
      <th> Column Types </th>
      <th>Required</th>
      <th>Numeric</th>
      <th>Disable</th>
      <th>Email</th>
      <th>Password</th>
      <th>DateTime</th>
      <th>Date</th>
    </tr>
    <%= form_tag(create_crud_path) do %>
      <% @table_info.each do |c| %>
        <tr>
          <td align="center"> <%= c.name  %> </td>
          <td align="center"> <%=c.type.to_s%></td>
          <% if (c.name =~ /id/i) %>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled', 1, :class=>"checked_tick"%><label class="checked_tick_label"></label></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
          <% elsif c.type.to_s == 'integer' %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'numeric', 1, :class=>"checked_tick"%><label class="checked_tick_label"></label><br/>
              <%= number_field_tag "#{c.name}[]", '', {:placeholder => "Min", :style=> "width:60px;"} %>
              <%= number_field_tag "#{c.name}[]", '', {:placeholder => "Max", :style => 'width:60px;'} %>
            </td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
          <% elsif c.type.to_s == 'string' %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'email'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'password'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'datetime'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'date'%></td>
          <% elsif c.type.to_s == 'text' %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
          <% elsif c.type.to_s == 'boolean' %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
          <% elsif c.type.to_s == 'datetime' %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'datetime', 1, :class=>"checked_tick"%><label class="checked_tick_label"></label></td>
            <td align="center"><%= image_tag("not-available.png", :size => '18x18') %></td>
          <% else %>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'required' %></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'numeric'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'disabled'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'email'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'password'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'datetime'%></td>
            <td align="center"><%= check_box_tag "#{c.name}[]", 'date'%></td>
          <% end %>
        </tr>
      <% end %>
    <%= submit_tag('Create') %>
    <% end %>
    <%#= link_to "Create CRUD", create_crud_path(@table), class: "btn" %> 
    <% Rails.application.routes%>
  </table>
</div>

<style>
.checked_tick {
  display:none;
}

.checked_tick_label {
  display: inline-block;
  background-image: url('<%= asset_path 'tick.png' %>');
  width: 30px;
  height: 30px;
}

</style>

app/views/welcome/tablelisting.html.erb
                         <div class="widget-body">
						<table>
						<tr>
							<th> Table Name </th>
							<th> Info List </th>
						</tr>
						<% @tables.each do |table| %>
						<tr>
							<td> <%= table[0] %> </td>
							<td> <%= link_to "Table info", table_info_path(table[0]) %> </td>
							<td> <%#= link_to "Create CRUD", create_crud_path(table[0]), class: "btn" %> </td>
						</tr>
						<% end %>
						</table>
						 </div>